name: First Workflow
on: workflow_dispatch #Aguarda o disparo manual do usuário
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Run Multiple Messages
        run: | # Adicione este símbolo para rodar multiplos comandos em um mesmo step
          echo "First message"
          echo "Second message!"
      - name: Print Goodbye
        run: echo "Done - Bye!"
      
